### ISSUE TITLE
java: exporting a package from system module java.base is not allowed with --release

### ISSUE THREAD

**Issue by hairyex5000** [fisherstevenk/kyberJCE#21]
Having issues with the following on build:

`java: exporting a package from system module java.base is not allowed with --release
`

Using Temurin 18.0.2 JDK --> sometimes a runtime error with the following:

`Exception in thread "main" java.lang.IllegalAccessError: class com.swiftcryptollc.crypto.provider.KyberJCE (in unnamed module @0x27abe2cd) cannot access class sun.security.util.SecurityConstants (in module java.base) because module java.base does not export sun.security.util to unnamed module @0x27abe2cd`

Thanks,

**Comment by fisherstevenk** [comment]
Apologies, but I haven't tried compiling this with Java 18.  I typically use only LTS versions (I haven't moved to 20 yet).

Can you simply use the signed jar?  

https://github.com/fisherstevenk/kyberJCE/releases/tag/v2.1.5

That release was compiled by Oracle JDK 17 and signed.

I know that's not actually an answer to your question...

**Comment by fisherstevenk** [comment]
So it does look like I finally need to sunset the sun packages and update this module for Java 16+.

**Comment by fisherstevenk** [comment]
Removed the sun.security requirement by pulling the source files in.  They have been refactored by removing methods and variables that are not required for this implementation.

https://github.com/fisherstevenk/kyberJCE/pull/22
